# Generated by Django 4.2.6 on 2023-11-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0003_retailsproductsunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailslocationcode',
            name='BusinessUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RetailsApis.retailsproductsunit', verbose_name='Business Unit'),
        ),
        migrations.DeleteModel(
            name='RetailsBusinessUnit',
        ),
    ]
