# Generated by Django 4.2.6 on 2023-11-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RetailsApis', '0004_alter_retailslocationcode_businessunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailscategories',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='retailseventalert',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailseventcategories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='retailslocationcode',
            name='BusinessUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsproductsunit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='retailsorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailstables'),
        ),
        migrations.AlterField(
            model_name='retailsproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AlterField(
            model_name='retailsproducts',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='retailsstorecode',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailslocationcode', verbose_name='Store Location'),
        ),
        migrations.AlterField(
            model_name='retailsstorecode',
            name='Process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RetailsApis.retailsprocessconfig', verbose_name='Process'),
        ),
    ]
