# Generated by Django 4.2.6 on 2023-11-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApis', '0004_alter_restaurantlocationcode_businessunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantcategories',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='restauranteventalert',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restauranteventcategories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='restaurantlocationcode',
            name='BusinessUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantproductsunit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='restaurantorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restauranttables'),
        ),
        migrations.AlterField(
            model_name='restaurantproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AlterField(
            model_name='restaurantproducts',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='restaurantstorecode',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantlocationcode', verbose_name='Store Location'),
        ),
        migrations.AlterField(
            model_name='restaurantstorecode',
            name='Process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestaurantApis.restaurantprocessconfig', verbose_name='Process'),
        ),
    ]
