# Generated by Django 4.2.6 on 2023-11-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0003_hotelproductsunit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotellocationcode',
            name='BusinessUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HotelApis.hotelproductsunit', verbose_name='Business Unit'),
        ),
        migrations.DeleteModel(
            name='HotelBusinessUnit',
        ),
    ]
