# Generated by Django 4.2.6 on 2023-11-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApis', '0004_alter_hotellocationcode_businessunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcategories',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='hoteleventalert',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteleventcategories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='hotellocationcode',
            name='BusinessUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelproductsunit', verbose_name='Business Unit'),
        ),
        migrations.AlterField(
            model_name='hotelorderitems',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelrooms'),
        ),
        migrations.AlterField(
            model_name='hotelorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteltables'),
        ),
        migrations.AlterField(
            model_name='hotelproducts',
            name='StoreBinCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelstorebincode', verbose_name='Store Bin Code'),
        ),
        migrations.AlterField(
            model_name='hotelproducts',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='hotelrooms',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelproductsunit', verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='hotelroomsorderitems',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hoteltables'),
        ),
        migrations.AlterField(
            model_name='hotelstorecode',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotellocationcode', verbose_name='Store Location'),
        ),
        migrations.AlterField(
            model_name='hotelstorecode',
            name='Process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelprocessconfig', verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='AccountSystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.accountsystem', verbose_name='Account System'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='GridDimensions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.griddimensions', verbose_name='Grid Dimensions'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='SigninTimeout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.signintimeout', verbose_name='Signin Timeout'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.userrole', verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='VatRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.vatrate', verbose_name='VAT Rate'),
        ),
        migrations.AlterField(
            model_name='roomsclasses',
            name='Unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApis.hotelproductsunit', verbose_name='Unit'),
        ),
    ]
